
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.calculator;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PARRGT = 4;
  public static final int PARLFT = 3;
  public static final int SUM = 5;
  public static final int NUMBER = 2;
  public static final int EOF = 0;
  public static final int DIV = 8;
  public static final int error = 1;
  public static final int MUL = 7;
  public static final int MIN = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMBER",
  "PARLFT",
  "PARRGT",
  "SUM",
  "MIN",
  "MUL",
  "DIV"
  };
}

